/**
 * Created by b on 2/14/2015.
 */

/**takes an array of config files generated by the UI and orchestrates the process of building the projections. **/

angular.module('cheatMealFinalProjectV2')
  .factory('Simulator', Simulator);

function Simulator(){

  return{
    run: run
  };

  function run(configs){

    var allResults = [];
    var graphPlotter = new GraphPlotter();
    var unitConverter = new UnitConverter();

    for(var i = 0; i < configs.length; i++){

      var bmrCalc = _BmrCalcFactory(configs[i].bmrCalcSelection);
      var changeCalc = new ChangeCalculator(configs[i], bmrCalc);
      var dateCalc = new DateCalculator(configs[i]);

      var result = {};

      result = new Plan(configs[i], changeCalc, dateCalc, graphPlotter, unitConverter).buildMetricPlan()
        .buildMetricGraph().convertMetricPlanToImperial().buildImperialGraph();

      allResults.push(result)
    }
    return allResults;
  }

  function _BmrCalcFactory(bmrCalcSelection){

      if(bmrCalcSelection === "Mifflin St Jeor"){
        return new MifflinStJeor;
      }
      if(bmrCalcSelection === "Harris Benedict"){
        return new HarrisBenedict;
      }
      if(bmrCalcSelection === "Katch McArdle"){
        return new KatchMcArdle;
      }

    //defaults to most accurate;
    return new MifflinStJeor;
  }


}
